apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVWmpiZHk0RWFBNWR2R082T0ZUeWkxOU0xUjd3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTFNVEF4TVRJd05UTXlNVm9YRFRJMU1URXhNREl3TlRNeU1Wb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXI0eG9FUFlXVWVUY01RTElCSnFRSXZJdFh4bnJzOXlRN2J5cQphT3Brd0l4Z1BoV0trdVFwaC81WGxKMy95c09UMzRrNVA1V0hLTHZNRGgzcWkxS01zQ0dtQVZDUEFQOERHWko1CnZkamFQdzFZdzJ3RG9VVTN5QWJCZnU3OGg5d1hEZDRveEdEbXp0N3R5UmFqa1RuZHdoYXB4ZGk5WE51Mm9objUKWUQyQVE1UjFXR2hsdVd2QXdteHRTWEdwcUh4UlZ5UUdIY3RLRll6U2lGMnYrU1ZJRTZJcitiMjR4MXFRVGIvTQoyQSt1aE0rUGNyUk9TSTl6OWhPMHphM1FVbkFLY0FBWmphTjFsM2lMN3RPbnMwUlVZL3hkTVFLZ2RVZWFRYWc4CnlrcGd6N0RTclhoNFFoNnVJQ2FCbnBRMk5xWlVTTTB6cVdDa0YzamtQdjdYQlBxMGFRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVQUVSYTBlOHV0U1diTmJPOVg3MkVKRVZZWVBRd0h3WURWUjBqQkJnd0ZvQVVBRVJhMGU4dQp0U1diTmJPOVg3MkVKRVZZWVBRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFaRkNLVVgxK1VIWXRaQlBTWG4zdGw4QmFZV29laVBUZGF2NG5udDU3VnJUTzBuYlZzekx3TGVTaXFQeWEKK0NLMitUbTVFN0JKc2hRaVRVWFlGd2VGUVVua0tOQ1dvNnpSUkpnVisrbHZPSTRwMmFaMG4xbkxvYnBiYTNVZwp0eDFnQlBrZ3hxMGI5WkJoQU1Ga2NCU28za0VoZ2JJT1ZtQ2crdTgveFV0V21ibXdKVWtMRW1KMUZyc2lEVEIrCmlCRzhtWkxnajk4bTl4N1A3bW5SV0Q2aDVWYmVxK3NJQ1NaUTIwNytRdTBDTWNxY21oZHZhdnFRcEJvU3ZYUisKN2pXdy9OQVUwVXZYYXZ3U2ljUkhZdVFmRzFuWEtXVE5nVGd4Z001NjU1QnN5dGtwN3pzRU9scGtZRDFGRzZuUgpmc3NjTG56NWJYWU01NWZTY0dsS09lTXd5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
