apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDurringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large

          - key: size
            operator: NotIn
            values:
            - Small

          - key: size
            operator: Exists


          - key: size
            operator: DoesNotExist
            values:
            - Small