apiVersion: v1
data:
  APP_COLOR: darkblue
  APP_OTHER: disregarded
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-15T21:05:19Z"
  name: webapp-config-map
  namespace: default
  resourceVersion: "1288"
  uid: 587392be-c274-4d61-81b1-ed5adc49193a


# Reference configmap key-value:
  # envFrom:
  # - configMapRef:
  #   name: webapp-config-map
  #   configMapKeyRef:
  #     valueFrom: APP_COLOR

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
  - name: webapp-color
    image: busybox
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: webapp-config-map
          key: APP_COLOR
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
