apiVersion: v1
kind: Pod
metadata:
  name: multi-init-container-pod
spec:
  containers:
    - name: nginx
      image: nginx
  initContainers:
    - name: init-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello, World!' > /var/www/html/index.html"]
      volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
    - name api-checker
      image: busybox
      command: ["sh", "-c", "while true; do curl http://localhost:80/index.html; sleep 10; done"]
      volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
    - name: logger
      image: busybox
      command: ["sh", "-c", "while true; do echo '$(date) - API check successful' >> /var/log/api-check.log; sleep 10; done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
      restartPolicy: Always
    volumes:
      - name: html-volume
        emptyDir: {}
      - name: log-volume
        emptyDir: {}