apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteOnce # change to ReadWiteMany for multiple pods to read and write to the same volume
  resources:
    requests:
      storage: 50Mi
