---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: event-simulator
    volumeMounts:
      - mountPath: /log
        name: pv-log-volume  # 
  volumes:
    - name: pv-log-volume
      persistentVolumeClaim:
        claimName: claim-log-1
