apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext: # this is set for the pod.
    runAsUser: 1001
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['sleep', '3600']
    securityContext: # this is set for the pod.
      runAsUser: 1002
      capabilities:
        add:
          - NET_ADMIN