apiVersion: v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  expirationSeconds: 86400
  - usages:
    - digital signature
    - key encipherment
    - server auth
  request: |
  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXZ3TGVMQ3kwblhIN2hDRUp1VFhFaE9wTEVUaUh6MGltYkxFeUl6VEZYOStTCitINkxsdXlqYUNCQnB2TGRabXhsa2FsSjgwdDd4RjFHTzBjejVmSHZaODBheURpWEliaU1NcXJ0VDQ3YXYyMnQKb3plQnJxWWhpTWgyU3JBRjlzUXZ5R3JiN1FTZG13TUVWWjlvYjVneEFkS0w3OEVhYzdnK2RkdXdxL3RnWVQrOApNUHIwMThTcjlzL1o1a29UbDRKdWRncW1mU2U4T1kxdDNDVTZlY2JSTlhNc0FRd3E0UHlzaytONEVOcWErdWorCjF2R3d6dGJkbHFKWDIvM3VDSWVLWXY4N2xrOVJ3SWJDWWJ2LzdHUlJteDZJWXpCc0lWMU5lK29mc21PYXdYTkgKeVBqZ1VPcE9acTFpOGNtRXV2ekErTGZtUEI5Y2ZRWlQxcW1JeFIxVGt3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQWpnTHFBV3FGZGI5dittK252SVp5bkhtbllVMm9pRFZzdml5UWM0eEJBY0RZVFU2Y3k4CnRMazZMbzQ0blNsNEV2cy9xbzZYbVRJWjJJYWhwSGpXeFRHVE1DOVhmK3YzTEJaSk5NVFlOMnIvd1ZsUFg3RjkKV3lvcytmWjRsSm1raERPNVhHQXh6cDBXZng0eGwyY2owVVE2SklkeTNwaFV3WEFXNTFGSHB0dnlaZytVbUdBZQpsTzlDTXJlR2ExcVVpNFBJSU1LM3VramRmUC94L1lpM0NVZTM2Y1ZOdXRyaVB0V0ZtOFlKMEE5Ym9QOUt6a09ZCnZSUm1ENFRNMDh4dXI0K1RYZ1NNMURqem55YmRiTWtCTkU4TVlsQ1pHNzdUVHZGYktpUm1uMDJOd2c3aFYwRU8KZ0hxQWVieVRnamphbHZqMGJENFZFdkN3bEx5NGxrUmt3clk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

