---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage  # name of the storage class to use
  resources:
    requests:
      storage: 1Gi

