apiVersion: v1
kind: Volume
metadata:
  name: secret-volume
spec:
  secret:
    secretName: secret-data
# ls /opt/secret-volume
# DB_Host DB_User DB_Password

cat /opt/secret-volume/DB_Host
cat /opt/secret-volume/DB_User
cat /opt/secret-volume/DB_Password
# pswrd