apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  serviceAccountName: secrets-store-csi-driver # This is the service account for the secrets store csi driver
  volumes: # This is the volume for the secrets store csi driver
   - name: db-creds
     csi: # This is the csi driver for the secrets store csi driver
       driver: secrets-store.csi.k8s.io # This is the driver for the secrets store csi driver
       readOnly: true # This is the read only flag for the secrets store csi driver
       volumeAttributes: # This is the volume attributes for the secrets store csi driver
         secretProviderClass: db-aws-secrets # This is the secret provider class for the secrets store csi driver
  containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80
     volumeMounts: # This is the volume mounts for the secrets store csi driver 
      - name: db-creds
        mountPath: /etc/db-creds
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}