apiVersion: v1
kind: Pod
metadata:
  name: inplace-pod-resizing
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP