apiVersion: v1
kind: Pod
metadata:
  name: manual-autoscaling
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m